<a href="https://colab.research.google.com/github/Daniel-UTEC/etl-data-pipeline-2503162022/blob/Temporal/cursos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
#Carga de datos
import pandas as pd

url = "https://raw.githubusercontent.com/Daniel-UTEC/etl-data-pipeline-2503162022/refs/heads/main/data/raw/A_cursos.csv"

df = pd.read_csv(url)

df.head()

  id_curso          curso         docente creditos
0     C200     Matemática  Lic. Hernández        3
1     C201   Programación     Mtra. Pérez        4
2     C202  Base de Datos    Mtra. Rivera        4
3     C203      Redacción      Ing. López        4
4     C204         Inglés     Ing. Romero        5

In [16]:
#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id_curso  13 non-null     object
 1   curso     13 non-null     object
 2   docente   13 non-null     object
 3   creditos  13 non-null     object
dtypes: object(4)
memory usage: 548.0+ bytes

id_curso    0
curso       0
docente     0
creditos    0
dtype: int64

In [26]:
#Limpieza de datos
cursos = df.copy()

cursos.columns = cursos.columns.str.strip().str.lower()

for col in cursos.select_dtypes(include='object').columns:
    cursos[col] = cursos[col].astype(str).str.strip()

cursos['docente'] = cursos['docente'].str.upper()

cursos = cursos.drop_duplicates()

cursos.columns = cursos.columns.str.strip()

cursos['curso'] = cursos['curso'].str.strip()

cursos['docente'] = cursos['docente'].str.strip()

cursos['creditos'] = cursos['creditos'].astype(str).str.replace(r'[a-zA-Z\s]+', '', regex=True)

cursos['creditos'] = pd.to_numeric(cursos['creditos'])

cursos['docente'] = cursos['docente'].str.title()

cursos = cursos.drop_duplicates()

cursos.head()

  id_curso          curso         docente  creditos
0     C200     Matemática  Lic. Hernández         3
1     C201   Programación     Mtra. Pérez         4
2     C202  Base de Datos    Mtra. Rivera         4
3     C203      Redacción      Ing. López         4
4     C204         Inglés     Ing. Romero         5

In [27]:
#Separar datos váildos y datos rechazados
validos = cursos[
    cursos['curso'].notna() &
    cursos['docente'].notna() &
    cursos['creditos'].notna()
].copy()

rechazados = cursos[
    cursos['curso'].isna() |
    cursos['docente'].isna() |
    cursos['creditos'].isna()
].copy()

In [28]:
#Colocar motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['curso']):
        motivos.append("curso_vacio")

    if pd.isna(row['docente']):
        motivos.append("docente_vacio")

    if pd.isna(row['creditos']):
        motivos.append("creditos_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [29]:
#Exportar archivos
validos.to_csv("cursos_curated.csv", index=False)

rechazados.to_csv("cursos_rejects.csv", index=False)

In [30]:
#Conectar con PostgreSql Cloud
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_xmjb_user:MOAOhCFp0RSnjSynN6hL6D6GkhyiuY6s@dpg-d6qu75khg0os73b4ghu0-a.oregon-postgres.render.com/etl_seguros_xmjb"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [33]:
#Carga de datos en PostgreSQL
validos.to_sql(
    'cursos_curated',
    engine,
    if_exists='replace',
    index=False
)

rechazados.to_sql(
    'cursos_rejects',
    engine,
    if_exists='replace',
    index=False
)

0

In [35]:
#validar la carga de datos
pd.read_sql(
"SELECT * FROM cursos_curated LIMIT 100",
engine
)

   id_curso          curso         docente  creditos
0      C200     Matemática  Lic. Hernández         3
1      C201   Programación     Mtra. Pérez         4
2      C202  Base de Datos    Mtra. Rivera         4
3      C203      Redacción      Ing. López         4
4      C204         Inglés     Ing. Romero         5
5      C205         Física     Mtra. Pérez         4
6      C206        Química    Lic. Morales         3
7      C207       Historia    Mtra. Rivera         4
8      C208    Estadística     Lic. Castro         3
9      C209          Ética    Mtra. Rivera         3
10     C210     Diseño Web     Mtra. Pérez         3
11     C211     Algoritmos     Ing. Romero         5