<a href="https://colab.research.google.com/github/Daniel-UTEC/etl-data-pipeline-2503162022/blob/Temporal/notas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Carga de datos
import pandas as pd

url = "https://raw.githubusercontent.com/Daniel-UTEC/etl-data-pipeline-2503162022/refs/heads/main/data/raw/A_notas.csv"

df = pd.read_csv(url)

df.head()

  id_nota id_estudiante id_curso nota  periodo
0   N5000         E1102     C204  7.9   I-2025
1   N5001         E1179     C205  8.1   I-2025
2   N5002         E1092     C202  8.6   I-2025
3   N5003         E1014     C211  8.0   I-2025
4   N5004         E1106     C208  7.4  II-2025

In [2]:
#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_nota        330 non-null    object
 1   id_estudiante  325 non-null    object
 2   id_curso       328 non-null    object
 3   nota           326 non-null    object
 4   periodo        330 non-null    object
dtypes: object(5)
memory usage: 13.0+ KB

id_nota          0
id_estudiante    5
id_curso         2
nota             4
periodo          0
dtype: int64

In [6]:
#Limpieza de datos
notas = df.copy()

notas.columns = notas.columns.str.strip().str.lower()

for col in notas.select_dtypes(include='object').columns:
    notas[col] = notas[col].astype(str).str.strip()

notas.columns = notas.columns.str.strip()

notas['id_nota'] = notas['id_nota'].str.strip()

notas['id_estudiante'] = notas['id_estudiante'].str.strip()

notas['id_curso'] = notas['id_curso'].str.strip()

notas['nota'] = notas['nota'].str.strip()

notas['periodo'] = notas['periodo'].str.strip()

notas['nota'] = notas['nota'].astype(str).str.replace(r'[a-zA-Z\sñÑáéíóúÁÉÍÓÚ]+', '', regex=True)

notas['nota'] = notas['nota'].astype(str).str.replace(r'[^0-9.]', '', regex=True)

# Convert to numeric, coercing errors to NaN
notas['nota'] = pd.to_numeric(notas['nota'], errors='coerce')

notas['nota'] = notas['nota'].round(1)

#print(notas['nota'])

notas = notas.drop_duplicates()

notas.head()

  id_nota id_estudiante id_curso  nota  periodo
0   N5000         E1102     C204   7.9   I-2025
1   N5001         E1179     C205   8.1   I-2025
2   N5002         E1092     C202   8.6   I-2025
3   N5003         E1014     C211   8.0   I-2025
4   N5004         E1106     C208   7.4  II-2025

In [12]:
#Separar datos válidos y datos rechazados
validos = notas[
    notas['id_nota'].notna() &
    (notas['id_estudiante'].astype(str).str.lower() != 'nan') &
    notas['id_curso'].notna() &
    (notas['id_curso'].astype(str).str.lower() != 'nan') &
    notas['nota'].notna() &
    notas['periodo'].notna()
].copy()

rechazados = notas[
    notas['id_nota'].isna() |
    (notas['id_estudiante'].astype(str).str.lower() == 'nan') |
    notas['id_curso'].isna() |
    (notas['id_curso'].astype(str).str.lower() == 'nan') |
    notas['nota'].isna() |
    notas['periodo'].isna()
].copy()

In [20]:
# Colocar motivo de rechazo
def motivo(row):
    motivos = []

    def es_vacio(valor):
        if pd.isna(valor):
            return True

        texto = str(valor).strip()

        if texto == "" or texto.lower() == "nan":
            return True

        return False

    if es_vacio(row['id_nota']):
        motivos.append("id_nota_vacio")

    if es_vacio(row['id_estudiante']):
        motivos.append("id_estudiante_vacio")

    if es_vacio(row['id_curso']):
        motivos.append("id_curso_vacio")

    if es_vacio(row['nota']):
        motivos.append("nota_vacio")

    if es_vacio(row['periodo']):
        motivos.append("periodo_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [19]:
#Exportar archivos
validos.to_csv("notas_curated.csv", index=False)

rechazados.to_csv("notas_rejects.csv", index=False)

In [21]:
#Conectar con PostgreSql Cloud
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_xmjb_user:MOAOhCFp0RSnjSynN6hL6D6GkhyiuY6s@dpg-d6qu75khg0os73b4ghu0-a.oregon-postgres.render.com/etl_seguros_xmjb"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [22]:
#Carga de datos en PostgreSQL
validos.to_sql(
    'notas_curated',
    engine,
    if_exists='replace',
    index=False
)

rechazados.to_sql(
    'notas_rejects',
    engine,
    if_exists='replace',
    index=False
)

27

In [23]:
#validar la carga de datos
pd.read_sql(
"SELECT * FROM estudiantes_curated LIMIT 10",
engine
)

  id_estudiante            nombre  edad                        correo
0         E1000        Raúl Gómez    26     carlos.castro45@correo.sv
1         E1001        Ana Castro    18    adriana.santos43@gmail.com
2         E1002   Ricardo Vásquez    23    maria.castro23@empresa.com
3         E1003       Sofía Gómez    27        luis.gomez77@correo.sv
4         E1004    Adriana Santos    26     elena.morales56@gmail.com
5         E1005      Carlos Pérez    26      diego.perez25empresa.com
6         E1006  Valeria Martínez    25      luis.romero1@outlook.com
7         E1007     Ana Hernández    22     elena.romero9@empresa.com
8         E1008    Carmen Vásquez    21   daniela.morales85@gmail.com
9         E1009      Andrés Mejía    20  natalia.rivera65@empresa.com

In [24]:
#validar la carga de datos
pd.read_sql(
"SELECT * FROM estudiantes_rejects LIMIT 10",
engine
)

,id_estudiante,nombre,edad,correo,motivo_rechazo
0,nan,Ana Santos,27,adriana.romero42@correo.sv,id_estudiante_vacio
1,nan,Gabriela Martínez,17,ricardo.ramirez84@gmail.com,id_estudiante_vacio
2,nan,Carlos Vásquez,22,ricardo.castro43@empresa.com,id_estudiante_vacio
3,nan,Miguel Morales,17,jose.guerrero28@empresa.com,id_estudiante_vacio
4,nan,Diego Mendoza,19,daniela.gomez98@outlook.com,id_estudiante_vacio
5,nan,Marta Romero,30,luis.morales96@correo.sv,id_estudiante_vacio
6,nan,Luis Pérez,24,valeria.ramirez10@correo.sv,id_estudiante_vacio
7,nan,Carlos Mejía,27,elena.romero19@outlook.com,id_estudiante_vacio